name: Nafas
options:
  bundleIdPrefix: com.midomj
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    DEVELOPMENT_TEAM: ""
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: YES

targets:
  Nafas:
    type: application
    platform: iOS
    sources:
      - path: Nafas
        excludes:
          - "**/.DS_Store"
    resources:
      - path: Nafas/Resources/Assets.xcassets
    info:
      path: Nafas/Resources/Info.plist
      properties:
        CFBundleDisplayName: Nafas
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        UILaunchScreen:
          UIColorName: ""
          UIImageRespectsSafeAreaInsets: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIUserInterfaceStyle: Dark
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        ITSAppUsesNonExemptEncryption: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.midomj.nafas
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: NO
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        SWIFT_EMIT_LOC_STRINGS: YES
